webui/src/Label.js
webui/src/bug/Bug.js
webui/src/list/BugRow.js

A hash is computed for each label, which is then used to determine the label's color.
In the future the label's colors might be somehow configurable, but at least they now have different colors.
(Part of the diff is due to [prettier](https://prettier.io) re-formatting the code)

Different colors for labels based on their hash

---

README.md

some persons made archlinux packages for git-bug:
* one to compile from git
* one to compile from the latest stable version
* one to get the binary from the latest release
i added that to the readme.
let me know if i did something wrong.

readme: added archlinux aur package in install section

---

termui/show_bug.go

Makes the key 'o' toggle a bug open or closed in the `termui` bug view. Feel free to bikeshed the specific key to activate this functionality (or even if a toggle behavior is appropriate).
I have very little experience with go, so if this isn't idiomatic, feel free to point it out.
Closes  #29.

Add open/close in bug view

---

cleaner/cleaner.go
commands/add.go
commands/bridge.go
commands/bridge_configure.go
commands/bridge_pull.go
commands/bridge_rm.go
commands/comment.go
commands/comment_add.go
commands/deselect.go
commands/label.go
commands/label_add.go
commands/label_rm.go
commands/ls-labels.go
commands/ls.go
commands/pull.go
commands/push.go
commands/select.go
commands/show.go
commands/status.go
commands/status_close.go
commands/status_open.go
commands/termui.go
commands/title.go
commands/title_edit.go
util/interrupt/cleaner.go
util/interrupt/cleaner_test.go

This PR attemps to solve issue #42 
I created a "cleaner" package where all lockfile removal functions will be registered, and in can any interruption signal is recieved, the these functions will be executed first.
As far as I know, there is no way to create unit tests for this. ~~I created an [Issue](https://github.com/auyer/git-bug/issues/1) on my fork in case someone figures out how to test this.~~
As far as manual tests go, I repetedly performend manual interruptions on a long running `git bug ls` several times, and killed the text editor responsible by `git bug add`. 
Please, test it with your test cases, and report the results here.

[WIP] Cleaning lock files on Interruption

---

README.md

Cloning a Go project is a weird thing for developers unfamiliar with the
language.
This closes #77.

README.md: Add developer-specific information.

---

bug/bug_actions_test.go
commands/select/select_test.go
tests/read_bugs_test.go

Some git operations require the user to have an identity configured and
will exit with failure if none is set (or if git can't guess it). As a
direct consequence of this, the test suite may fail depending on the
user local configuration.
The error itself is justified as regular users *should* configure their
identity themselves. However, when building in chrooted environments
it's unlikely the git identity will be set making the test suite fail
unnecessarily.
To prevent such unnecessary failures, let's make a dummy identity for
repos created and used by the test suite.

tests: configure user ident in repos used by tests

---

bug/op_add_comment.go
bug/operation_test.go
commands/show.go

Some bug trackers, like Launchpad, allow messages to be empty (when adding a
file to the bug, for instance).

Allow empty messages in comments.

---

bug/snapshot.go

After some fight with my git, here is the best fix I can actually do for the short id format issue. May be some there are aother alternate HumanID() implementation somewhere. I didn't find any by doing basic search with grep.

Issue #87: use same id format function in snapshot.go than in bug.go

---

commands/ls-id.go

Adding check for length of args
Pulling bugIds from correct backend.

ls-id.go: Fixing ls-id

---

commands/comment.go
commands/comment_add.go
commands/label.go
commands/label_add.go
commands/label_rm.go
commands/select.go
commands/select/select.go
commands/title.go
commands/title_edit.go
commands/user.go
commands/user_adopt.go

Hey @MichaelMure ! Ça roule?
I was getting started with the tool and got a bit confused when I tried to add a label. I thought it was creating a list of labels... So I thought I would give a bit more clues on these commands by adding a bit more info.
- Informed that label command adds/removes a label to a given bug.
- Added suggestion to use select command when omitting to provide a bug id as argument.
- Added a bit more detail for the select command documentation, giving a hint to "deselect" command.

Select and Label command documentation

---

webui/package-lock.json
webui/package.json

```
@material-ui/core: 1.5.1 → 3.9.3
@material-ui/icons: 2.0.3 → 3.0.2
apollo-boost: 0.1.23 → 0.3.1
graphql: 14.0.2 → 14.2.0
moment: 2.23.0 → 2.24.0
react: 16.7.0 → 16.8.6
react-apollo: 2.3.3 → 2.5.3
react-dom: 16.7.0 → 16.8.6
react-router: 4.3.1 → 5.0.0
react-router-dom: 4.3.1 → 5.0.0
react-scripts: 2.1.3 → 2.1.8
eslint-config-prettier: 3.3.0 → 4.1.0
eslint-plugin-prettier: 2.7.0 → 3.0.1
prettier: 1.15.3 → 1.16.4
```
---
I haven't packed the assets to avoid conflicts.

webui: Upgrade dependencies

---

cache/filter.go

Fixed filter query for multiple labels from
`OR` to `AND` according to github conventions.
Fixed https://github.com/MichaelMure/git-bug/issues/115

cache/filter.go: Fix query match for --label 

---

commands/ls.go

commands: ls fix CJK characters out of alignment

---

bridge/bridges.go
bridge/core/bridge.go
bridge/github/config.go
bridge/launchpad/config.go
commands/bridge_pull.go
commands/bridge_rm.go

[bridge] Change bridge name format in the config

---

commands/bridge_rm.go
identity/identity.go
repository/git.go
repository/git_test.go
repository/mock_repo.go

- Add `RmConfigSection` to `RepoCommon` interface
- Add tests cases for `RmConfigSection`
- Fix `git bug bridge rm` expected behaviour by using `RmConfigSection`

Fix bridge rm command

---

bridge/gitlab/import.go

bridge/gitlab: handle all known notes types

---

Gopkg.lock
Gopkg.toml
bridge/core/bridge.go
bridge/core/export.go
bridge/core/import.go
bridge/core/interfaces.go
bridge/github/export.go
bridge/github/export_test.go
bridge/github/import.go
bridge/github/import_test.go
bridge/github/iterator.go
bridge/gitlab/import.go
bridge/gitlab/import_notes.go
bridge/gitlab/import_test.go
bridge/gitlab/iterator.go
bridge/launchpad/import.go
bridge/launchpad/launchpad_api.go
cache/repo_cache.go
commands/bridge_pull.go
commands/bridge_push.go
entity/merge.go
vendor/golang.org/x/sync/AUTHORS
vendor/golang.org/x/sync/CONTRIBUTORS
vendor/golang.org/x/sync/LICENSE
vendor/golang.org/x/sync/PATENTS
vendor/golang.org/x/sync/errgroup/errgroup.go

Bridge: pull/push enhancements

---

bridge/github/export.go
bridge/github/export_test.go
bridge/github/import_query.go

- import all existing labels at Github before start export task
- fix #176

bridge: Github exporter support case sensitive labels

---

cache/repo_cache.go
commands/select/select.go
input/input.go
repository/git.go
repository/git_testing.go

Since is returns the .git dir directly, it is not more needed to
concatenate .git.

issue 178: fetch the repo dir with rev-parse --git-dir

---

bridge/core/auth/credential.go
bridge/core/auth/token.go
bridge/core/bridge.go
bridge/github/config.go
bridge/github/import.go
bridge/github/import_test.go
bridge/gitlab/config.go
bridge/gitlab/import.go
bridge/gitlab/import_test.go
commands/bridge_auth.go
commands/bridge_auth_show.go
commands/bridge_configure.go
commands/bridge_pull.go
commands/user_adopt.go

I was writing a how-to to explain how to use git-bug as a remote for an external bugtracker and I realized I was not happy with the UX. The problem is that you have to 1) create a temporary user, 2) configure the bridge, 3) pull the bugs and identities and 4) adopt the actual identity you want to use.
This PR change that to a simpler workflow: 1) configure the bridge, 2) pull the bugs and identities and 3) adopt your user. This is done by assigning a temporary "default user" to the new credential that will be set properly later when `user adopt` is run.
Detail is as follow:
- init() only the importer or exporter as required
- assign a "default user" user Id to credentials at creation if no user has been set
- `bridge auth`: also display the user
- `bridge auth show`: adapt to a potential …

bridge: allow to configure and pull without having set a user first

---

bridge/core/bridge.go
bridge/core/export.go
bridge/core/import.go
bridge/github/import.go
repository/config_git.go

This PR is an attempt to fix #286 
My understanding is that when trying to import a comment edition, if the original comment is nowhere to be found locally the import will hard fail with an error. This kinda make sense because the comment really should be there but that also an assumption we can relax a bit I think. A warning might be enough.
@cheshirekow I cherry-picked from your PR the two commits introducing warning in the bridge's core (one completely, one while remove the Jira related changes). Rebasing your PR should go without too much though.

Github import error

---

bridge/core/auth/credential.go
bridge/core/auth/credential_base.go
bridge/core/auth/credential_test.go
bridge/core/auth/login.go
bridge/core/auth/login_password.go
bridge/core/auth/login_password_test.go
bridge/core/auth/login_test.go
bridge/core/auth/token.go
bridge/core/auth/token_test.go
bridge/github/config.go
bridge/github/config_test.go
bridge/github/export_test.go
bridge/github/import_test.go
bridge/gitlab/config.go
bridge/gitlab/export_test.go
bridge/gitlab/import_test.go
commands/bridge_auth_addtoken.go

@cheshirekow this PR introduce two new kind of credentials: LoginPassword and Login
Bridges can use those to store either a tuple Login+Password or just the Login. Bridges have the liberty and the responsibility to exploit them as make sense. In particular, the Jira bridge will need to ask the user for the password when required if Login is used.
Sounds good to you ? Do you think it's really needed to store those in a different place than the git config as you have done in the Jira bridge ?

auth: refactor and introduce Login and LoginPassword, salt IDs

---

bridge/jira/client.go
bridge/jira/config.go
bridge/jira/export.go
bridge/jira/import.go
bridge/jira/jira.go

@cheshirekow this PR adapt the Jira bridge to the credential system and to all the refactor I did recently. Please have a look
Note: It compiles but I can't test myself (automated tests would be veeery useful).
Note: the base of this PR is your branch pushed on this remote, otherwise I can't PR on it
A few questions:
- do you think it would be possible to detect automatically the credential (session or token) ? That would simplify both the code and the UX
- there is a mismatch between the name and value of this constant, what's the good concept ? metaKeyJiraOperationId = "jira-derived-id"
- it looks it would be very easy to support the official hosted Jira instances, it should simply be a default value in the baseURL prompt (see gitlab). What do you think ?

jira: rework to use the credential system + adapt to refactors

---

bridge/github/config.go
bridge/github/export.go
bridge/github/export_test.go
bridge/github/github.go
bridge/github/import.go
bridge/github/import_test.go
bridge/gitlab/config.go
bridge/gitlab/export_test.go
bridge/gitlab/gitlab.go
bridge/gitlab/import.go
bridge/gitlab/import_test.go
bridge/jira/config.go
bridge/jira/import.go
bridge/jira/jira.go
bridge/launchpad/config.go
input/prompt.go

> > But what if you need to use two different account for two different bridges?
> 
> So, that would only matter for importing a private repo. For importing a public repo, any credential would do. For exporting, the bridge will match credentials based on the login, using whatever credential is needed for this specific piece of data.
> 
> So what could be done is for the bridges to store an additional information in their config: the login to use when importing (ie, the one used during the configuration). That would make more sense than using the first random one found.
> 
> _Originally posted by @MichaelMure in [#250 (comment)](https://github.com/MichaelMure/git-bug/pull/250#issuecomment-587625833)_
fix #338

bridge: record the login used during the configure and use it as default credential

---

input/prompt.go

This fixes a compile error on Windows:
```
go generate
input\prompt.go:94:37: cannot use syscall.Stdin (type syscall.Handle) as type int in argument to terminal.GetState
input\prompt.go:100:26: cannot use syscall.Stdin (type syscall.Handle) as type int in argument to terminal.Restore
input\prompt.go:108:45: cannot use syscall.Stdin (type syscall.Handle) as type int in argument to terminal.ReadPassword
git-bug.go:1: running "go": exit status 2
make: *** [Makefile:18: build] Error 1
```

Fix compile errors on Windows

---

repository/config_git.go

I like to have "private" settings in a git include file, and store the
main .gitconfig under version control. I do not want any authentication
keys or tokens (even if encrypted) in version control, so I have by main
.gitconfig include another file which is local and not tracked.
The current implementation calls `git config --global --get-regexp
<keyPrefix>` and for some reason, this command does not follow git
include files.
The changes suggested in this PR add the `--includes` flag to the
command, which then reads any included files.

Supports git config includes

---

termui/bug_table.go

Nothing prevented you from pressing Enter in bug listing even when there
were no open bugs. Doing so resulted in:
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/MichaelMure/git-bug/termui.(*bugTable).openBug(0xc00007aa80, 0xc000354000, 0xc00036c120, 0x2, 0x2)
/build/source/termui/bug_table.go:440 +0x17f
github.com/awesome-gocui/gocui.(*Gui).execKeybinding(0xc000354000, 0xc00036c120, 0xc0003102a0, 0xc00007a001, 0xc000225b2c, 0xc000000180)
/build/go/pkg/mod/github.com/awesome-gocui/gocui@v0.6.1-0.20191115151952-a34ffb055986/gui.go:808 +0x65
github.com/awesome-gocui/gocui.(*Gui).execKeybindings(0xc000354000, 0xc00036c120, 0xc000225b38, 0x3, 0x4, 0x3)
/build/go/pkg/mod/github.com/awesome-gocui/gocui@v0.6.1-0.20191115151952-a34ffb055986/gui.go:787 …

termui: fix a crash when trying to open a bug when there are none

---

bridge/github/export.go
bridge/gitlab/export.go
bridge/jira/export.go
bug/op_create.go
bug/op_create_test.go
bug/operation.go
bug/snapshot.go
cache/bug_excerpt.go
cache/repo_cache.go
commands/json_common.go
commands/ls.go
commands/show.go
commands/user_ls.go
doc/man/git-bug-ls.1
doc/man/git-bug-show.1
doc/man/git-bug-user-ls.1
doc/md/git-bug_ls.md
doc/md/git-bug_show.md
doc/md/git-bug_user_ls.md
graphql/models/lazy_bug.go
misc/bash_completion/git-bug
misc/powershell_completion/git-bug
misc/zsh_completion/git-bug
termui/bug_table.go
termui/show_bug.go

This PR adds flags to the mentioned commands which allow the user to specify what output format they would like the commands to output in.
In addition, this adds support for a new output flag: `org-mode`, a format used by emacs users. Hopefully, this improves the functionality of the commands.
Example org-mode outputs:
- ls:
```
* 04174ef Open [2020-05-23 18:01:27 +0800 CST] karlicoss (karlicoss): [https://github.com/MichaelMure/git-bug/issues/392][feature: ls dump issues as plaintext (markdown/org-mode)] :[CLI:bridge:enhancement]:
** Last Edited: 2020-06-18 19:59:59 +0800 CST
** Actors:
: 528f341 karlicoss (karlicoss)
: 571aa44 Michael Muré (MichaelMure)
: ff7d2b9 vince
** Participants:
: 528f341 karlicoss (karlicoss)
: 571aa44 Michael Muré (MichaelMure)
: ff7d2b9 vince
```
- show:
``` …
```

Add formatting options to the 'show' and 'user ls' commands

---

commands/ls.go

- fix and align OPEN/CLOSED states
- fix org-mode links format
- santize tags (org-mode only allows _ and @ as special characters)
- format datetimes as org-mode
Follow up of https://github.com/MichaelMure/git-bug/issues/392 and https://github.com/MichaelMure/git-bug/pull/410

ls --format org-mode enhancements

---

commands/ls.go
termui/bug_table.go

I've been working on a GH repository which includes a lot of leading whitespace in issues due to a template including it.
I think the bug data shouldn't be altered, but it still makes sense to strip titles in list/table views so that more of the bug title is readily visible. The WebUI probably does that implicitly, while I'm unsure about other modes.

Trim titles in list views

---

termui/bug_table.go
termui/label_select.go
termui/show_bug.go

Always set the Fg color when Bg is set. This fixes poor contrast on
terminals with non-standard foreground colors.

Set the Fg color of the status bar to White

---

bug/bug.go
bug/bug_test.go
cache/repo_cache_bug.go
cache/repo_cache_test.go
commands/rm.go
commands/root.go

This PR adds a rm command, with usage `rm <id> [<remote>]`.  
This will remove a bug locally by its bug prefix and, if specified, the name of the remote it was imported from, addressing #66.
Note this does not support removing remote bugs, as pushing deletes is not recommended. In the future, if a feature is added to selectively import remote bugs, perhaps that issue can be addressed there.

Add the 'rm' command

---

cache/bug_cache.go
cache/repo_cache_test.go

This introduces locking into the bugcache for future updates.
Changes:
- Bugcache has Lock and Unlock methods for locking and unlocking
- Snapshot method on bugcache returns a copy of the snapshot
- Bugcache is locked internally when writing

Cache lock

---

bug/bug.go
bug/bug_actions.go
bug/bug_actions_test.go
bug/bug_test.go
bug/clocks.go
bug/operation_iterator_test.go
bug/operation_pack.go
bug/operation_test.go
cache/bug_excerpt.go
cache/identity_cache.go
cache/repo_cache.go
cache/repo_cache_bug.go
cache/resolvers.go
identity/bare.go
identity/identity.go
identity/identity_actions_test.go
identity/identity_stub.go
identity/interface.go
identity/resolver.go
misc/random_bugs/create_random_bugs.go
tests/read_bugs_test.go

- bug doesn't commit identities anymore, only make sure they are commit
- cache use an IdentityResolver to attach cached identities to bugs (deps injection): this make sure that we don't load multiple version of the same identity and improve perfs
- IdentityCache now are identity.Interface
- some naming simplification

cache,bug,identity: structural change

---

bridge/gitlab/import.go
go.sum

Fixes #481. This cleans the title of bugs imported from gitlab, similar to how the description is also cleaned upon import.

cleanup title on gitlab import

---

bridge/github/config.go

Fix issue #484
Suggestions for changes/improvements are very welcome.

Replace Github authorization endpoint by device authorization grant

---

bug/operation_pack.go
entity/err.go
identity/version.go

this commit exposes the format version of the operation pack and identity to reduce the changes needed in vendored code when migrating. This also creates error variables that can be propagated and tested against for migrations.

expose format version

---

webui/src/components/BugTitleForm/BugTitleForm.tsx
webui/src/components/CloseBugButton/CloseBugButton.tsx
webui/src/components/ReopenBugButton/ReopenBugButton.tsx
webui/src/pages/bug/CommentForm.tsx
webui/src/pages/list/ListQuery.tsx
webui/src/pages/new/NewBugPage.tsx

Why were the buttons captions changed, too? 
See Michaels reply: https://github.com/GlancingMind/git-bug/pull/31#issuecomment-798921866

WebUI: Fix hover-color of green buttons and caption

---

webui/package-lock.json
webui/package.json
webui/src/components/CommentInput/CommentInput.tsx
webui/src/components/Content/AnchorTag.tsx
webui/src/components/Content/BlockQuoteTag.tsx
webui/src/components/Content/ImageTag.tsx
webui/src/components/Content/index.tsx
webui/src/pages/bug/CommentForm.tsx
webui/src/pages/bug/Message.tsx
webui/src/pages/bug/MessageHistoryDialog.tsx
webui/types/remark-gemoji/index.d.ts

Closes #579 
Add/Fix support of markdown rendering for:
- Bug description
- Bug comment
- Comment history
Introduces following (changes) custom markdown elements:
- Add custom BlockQuoteTag to style quotes.
- Add custom AnchorTag to style anchors and support linking within the SPA.
- - E.g. following links should be equivalent `/bug/abc`, `localhost:3000/bug/abc`, both will link withing the SPA.
-  Always add line break after an image tag to prevent text to be inline with an image.

WebUI: Fix and improve rendering of markdown elements

---

bridge/github/config.go

GitHub have introduced a new format for their access tokens, which does
not fit within the rules of the previous regex. For the time being, the
previous token format is still being supported by GitHub, so it makes
sense to continue allowing legacy tokens.
https://github.blog/changelog/2021-03-04-authentication-token-format-updates/

Support new GitHub token formats

---

webui/src/components/Header/Header.tsx
webui/src/components/Themer.tsx

Somehow the icon-color of the theme switcher button in the packed WebUI is not the same of the dev version.
This PR should fix this issue.

WebUI: Fix theme switcher icon color in release

---

webui/src/__tests__/query.ts
webui/src/pages/list/Filter.tsx
webui/src/pages/list/FilterToolbar.tsx

Fix https://github.com/MichaelMure/git-bug/issues/655#issuecomment-829140370
The parse function dropped user given quotes. This resulted into a wrong formated query to the backend, which further lead to an error. This error then prevented the WebUI from displaying the proper bug count.

WebUI: Fix quoted filter strings

---

bridge/core/export.go
bridge/github/client.go
bridge/github/config.go
bridge/github/export.go
bridge/github/github.go
bridge/github/import.go
bridge/github/import_mediator.go
bridge/github/import_query.go

I wrote a new struct `client` which handles all the calls to the Github GraphQL API and which deals with the rate limit in a single place.
Note: work in progress; some manual testing is still needed.

feature: Github bridge mutation rate limit

---

bridge/github/import.go

Fixes #690
Rationale: When we export the bug instance, we only set `githubID` and `githubURL` (bridge/github/export.go:469)

Fix: github bridge: push then pull without duplication

---

bridge/gitlab/config.go

What's shown currently:
> You can generate a new token by visiting [https:/gitlab.com/profile/personal_access_tokens](https:/gitlab.com/profile/personal_access_tokens).

Fix GitLab access tokens settings link

---

commands/bridge_auth_addtoken.go
commands/bridge_auth_rm.go
commands/bridge_auth_show.go
commands/bridge_configure.go
commands/bridge_pull.go
commands/bridge_push.go
commands/bridge_rm.go
commands/comment.go
commands/comment_add.go
commands/helper_completion.go
commands/label.go
commands/label_add.go
commands/label_rm.go
commands/ls.go
commands/ls_test.go
commands/pull.go
commands/push.go
commands/rm.go
commands/root.go
commands/select.go
commands/show.go
commands/status.go
commands/title.go
commands/title_edit.go
commands/user.go
commands/user_adopt.go
commands/user_ls.go
misc/bash_completion/git-bug
misc/gen_completion.go

This completes bug IDs in bash and fish.  I haven't gotten completions to work in zsh.
In fish, the bug titles are shown as completion label, and can be searched for.
I don't know if/how other shells can show the completion label.
Maybe they don't use "\t" as separator but it seems to do no harm.
The interface does not yet seem ideal because sometimes subcommands and
bug IDs are both valid. Since there can be lots of bug IDs, they overshadow
the subcommands.
I wonder if instead of
git bug status open 0123acd
we should use
git bug status --open 0123acd
or if there's some other way to avoid ambiguity.
If that doesn't work out, fish has a -k/--keep-order flag, so subcommand
completions can be listed before bug IDs, but that's neither portable nor
a pretty solution.
Part of #493

Complete bug IDs where appropriate

---

api/graphql/models/lazy_bug.go
api/graphql/models/lazy_identity.go

Fix one the issue mentioned in https://github.com/MichaelMure/git-bug/issues/810

graphql: fix two invalid mutex lock leading to data races

---

bridge/github/client.go
bridge/github/export.go
bridge/github/import_events.go
bridge/github/import_mediator.go

I believe the issue was twofold:
When done importing, the calling context is likely still valid, so if the output channel is not read enough and reach capacity, some event producer down the line can be blocked trying to send in that channel. When closing it, this send is still trying to proceed, which is illegal in go.
In rateLimitHandlerClient, there was a need to 2 different type of output channel: core.ExportResult and ImportEvent. To do so, the previous code was using a single channel type RateLimitingEvent and a series of goroutines to read/cast/send to the final channel. This could result in more async goroutine being stuck trying to send in an at-capacity channel. Instead, the code now use a simple synchronous callback to directly push to the final output channel. No concurrency …

Github: fix data race

---

commands/ls.go
commands/ls_test.go

This change results in no (visible) change to the `ls` command's default formatter - the single space separating the bug prefix from the state is simply replaced by a tab (which will also position the state in the ninth column when tab widths are 2, 4 or 8 spaces.  Output from the command will be formatted as follows:
```
smoyer1@xps-15-7:~/git/git-bug$ git bug ls | head
f509b69 closed  CLI UX need refinements                      ◼ ◼ ◼      Alexandre Fran…  17 💬
8310415 closed  Serialization format                           ◼ ◼      Michael Muré (…  26 💬
0e2428a closed  Graphql schema is not documented                 ◼      Michael Muré (…
cd6935a closed  feat: Github import                          ◼ ◼ ◼      Michael Muré (…  35 💬
3dbe3bc open    feat: git-bug should store metadata for …
```

feat(836): updates default `ls` formatter for TSV output

---

commands/label.go
commands/label_ls.go
doc/man/git-bug-label-ls.1
doc/man/git-bug-label.1
doc/man/git-bug.1
doc/md/git-bug.md
doc/md/git-bug_label.md
doc/md/git-bug_label_ls.md

The discussion in #530 surrounding reorganizing the `git-bug` commands around the various entities that are defined (bug, board, pr, user, etc) isn't finished but the idea of changing the command to `git-bug label ls`list the valid labels to `git-bug label ls` still has merit:
This form is consistent with how the other sub-commands are structure and eliminates the last hyphenated command.  Whether or not, #530 moves forward, I think this syntax makes sense.
Note that the `git-bug ls-label` command has been deprecated in the same way as `ls-id` (with a notice that it will be removed for v1.0.

feat(530): make label commands consistent

---

bridge/github/client.go

It seems like the error message that github return changed.

github: fix rate limiting

---

doc/README.md

Just a small update to make the entry descriptions more consistent and readable.

doc/README: normalize verb tense and fix typo

---

cache/repo_cache_test.go

As seen on PR #933 and others, it's common for the Windows test suite to fail when run via GitHub Actions.  In that PR, @zinderic also noted that it's less prevalent but can also occur on Mac OSX.
I can't test on Mac OSX but on the `ext4` file system, the `TempDir` is deleted but it's asynchronous and only occurs when there are no open file handles (when the `go test ./...` ends).  On Windows, removing the temporary directory is (more?) synchronous and so Go waits for the OS to remove the `TempDir` while the OS is waiting for the open file handlers to be closed.
As seen in the changed file, the solution is to explicitly close both instances of the cache as soon as they're no longer needed.  I don't quite understand why the other cache tests don't have this problem but my intuition says …

fix(TestCache): eliminate hanging Windows tests

---

commands/bug/testenv/testenv.go

fix(commands): run tests in ./commands/... without ANSI color

---

cache/bug_subcache.go
cache/identity_subcache.go
cache/repo_cache.go
cache/repo_cache_common.go
cache/repo_cache_test.go
cache/subcache.go
commands/root.go
commands/wipe.go
doc/man/git-bug-wipe.1
doc/man/git-bug.1
doc/md/git-bug.md
doc/md/git-bug_wipe.md
entities/bug/bug_actions.go
entities/identity/identity.go
entities/identity/identity_actions.go
entities/identity/identity_test.go
entities/identity/identity_user.go
entity/dag/entity_actions.go
entity/dag/entity_actions_test.go
go.mod
go.sum
repository/gogit.go
repository/index_bleve.go
repository/localstorage_billy.go
repository/mock_repo.go
repository/repo.go
repository/repo_testing.go

Related to https://github.com/MichaelMure/git-bug/issues/676
I've added subcommand called "cleanup" which removes local bugs and identities.

add cleanup sub-command that remove local bugs and identities

---

bridge/gitlab/event.go
bridge/gitlab/import.go

Added the event **EventMentionedInCommit** in the gitlab bridge to support / not give an error on events in gitlab issue s where an issue ID is mentioned in a commit message.
See issue #973

added EventMentionedInCommit

---

commands/execenv/env.go
commands/execenv/env_test.go
commands/execenv/env_testing.go
commands/execenv/loading.go

In support of #831 and #993, this PR adds the ability to detect whether input is coming from the terminal or is being redirected/piped into the `git-bug` application as well as the corollary of output going to the terminal or being output to another application or file.
In general, there seem to be three categories of output for commands:
1. Commands that have the same output regardless of how they're being used such as listing bugs in the JSON format.
2. Commands that write the human readable portion of their output to `os.StdErr` and the machine-readable portion of their output to `os.StdOut` such as the output when creating a new bug (the id of the new bug should be written to StdOut and the " created" suffix should be written to StdErr.)
3. Commands that need different behavior …

feat: detect `os.Stdin`/`os.Stdout` redirection/pipe mode

---

commands/bug/bug.go
commands/bug/bug_comment_test.go
commands/bug/bug_test.go
commands/execenv/env.go
commands/execenv/env_testing.go
doc/man/git-bug-bridge-new.1
doc/man/git-bug-bug.1
doc/md/git-bug_bridge_new.md
doc/md/git-bug_bug.md
entity/id.go
entity/id_interleaved.go

@smoyer64 thought on this and on generalizing this pattern?

command: adapt the output of the bug list to the terminal size

---

commands/bug/bug.go
commands/bug/bug_test.go
doc/man/git-bug-bug.1
doc/md/git-bug_bug.md

I'm not fully sure if that's the right way. The important difference is that it doesn't impact the doc, keeping "default" here as the default value instead of removing entirely.

commands: different pattern to detect changed flags

---

Makefile
commands/root.go
doc/man/git-bug-bridge-new.1
doc/md/git-bug_bridge_new.md

Resolves #928 
In Go 1.18+ `debug.ReadBuildInfo` contains revision so we can read it from there when we are installing git-bug with `go install`.
In this PR we are utilizing the following attributes of `debug.BuildInfo`:
- `vcs.revision` - get commit hash
- `vcs.modified` - identifies whether the state of project is clean
- `vcs.time` - in discussion
This change introduces new version schema:
- `v0.8.0` - release
- `v0.8.0-dev-xyxyxy` - non release, at commit `xyxyxy`
- `v0.8.0-dev-xyxyxy-dirty` - same as above, but also dirty
- `dev-xyxyxy` - we don't know the tag, at commit `xyxyxy`
- `dev-xyxyxy-dirty` - same but also dirty

Fixed version info be set when go install

---

repository/gogit.go
repository/gogit_test.go

Altered logic for detecting git directory. Instead of erroring on non-direcctory .git files, now parses the file and returns the linked gitdir.
Note that since the module is a different repository, you have to `git bug user new` in the submodule before using git-bug. I've never used working trees, so I haven't tested that.
Also, I'm brand new to this project and haven't quite worked out how to add a unit test for this. Happy to do that if needed before this PR can be accepted.

fix(#971): parse submodule .git files instead of erroring

---

README.md

When cloning this repo for installation (as opposed to development), users should use the HTTPS url for this repo, as they almost certainly do not have the necessary access rights to clone via SSH.

Use HTTPS repo url

---

.github/workflows/presubmit.yml

```
fix: run the presubmit pipeline for PRs
commit 5eabe549e4f7fc98bbdf4e7b285cec00e5da4e99 refactored the workflows
so that they were orchestrated with reusable workflows. an unintended
side-effect of the rules that were created prevents the presubmit
pipeline from executing for pull requests made against this repository.
this change refactors this, so that the presubmit pipeline will _only_
run for pull requests against the default tree of this repository. we
explicitly remove the `on: push` event for it, in order to avoid overlap
that will occur for commits made in this repository that are also part
of a PR.
Change-Id: I56abc35c98cc40a06066952f2b6ed9194b1ab903
```

fix: run the presubmit pipeline for PRs

---

.github/workflows/cron.yml
.github/workflows/lifecycle.yml

```
feat: improved lifecycle management with stale-bot
This change refactors the automatic lifecycle management workflow that
uses the `stale-bot` action library, such that neither issues nor pull
requests will be closed.
An additional label of `lifecycle/rotten` has been added to indicate
issues or pull requests which have been inactive for 180 days or more.
Change-Id: Ia748552c91ada43b4a762879db469132131956f0
```

feat: improved lifecycle management with stale-bot

---

.github/workflows/presubmit.yml

```
feat(ci): support a merge queue
This change adds support for using the [Merge Queue][0] merge method.
This still needs to be enforced at the repository level.
[0]: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
Change-Id: I4b464818c0cd82d1d56c4dd7f807f6cfc5dfa913
```

feat(ci): support a merge queue

---

flake.nix

This change adds `delve`, the de facto debugger for go, to the
development shell..
Change-Id: I0bcda2b3569926dc16d8cbd653845f371ef33452

feat: add package to dev shell: delve

---

bridge/github/config_test.go
bridge/github/import_test.go

This change renames references to the repository used to test the github
bridge from `git-bug-test-github-bridge` to `test-github-bridge`,
dropping the `git-bug` prefix as it is extraneous now that it is under
the `git-bug` organization.
Change-Id: I5795bd39cc3b2e81774c4d9676ae5cbabfba8f1c

refactor: rename github test repository: test-github-bridge

---

README.md

The old room has a message from ﻿sudoforge saying
> 👋 hi there! this is just a friendly message noting that the source of truth for the community is moving off of gitter's server, onto the matrix foundation's public server. the address for that room is: 
[git-bug](https://matrix.to/#/#git-bug:matrix.org)
And the new room has:
> 👋 hey folks. this [matrix.org](http://matrix.org/) room is going to become the source of truth for the git-bug community. let me know if you have any questions!

Update README.md Matrix link to new room

---

.github/dependabot.yml

This reverts commit cc3b7c328dd4e4ad51de15919962d62f1146ca51,
effectively disabling Dependabot. This is being done primarily due to
git-bug/git-bug#1367, but also because the implementation of this bot is
noisy and often broken (failing to run `go mod tidy`, resulting in a CI
error that requires manual intervention to fix).
Automatically updating dependencies is helpful, but not a priority right
now. In the future, it is possible to revert this commit, however, I
would suggest looking at renovate [0] as an alternative approach, as I
personally find it to be far less invasive/noisy (see #1247).
[0]: https://docs.renovatebot.com/
Change-Id: I32f06381e1abf66a2655b5b6ba5c96cca6124720

revert: "Create Dependabot config file"

---

bridge/gitlab/event.go
bridge/gitlab/event_test.go
bridge/gitlab/export_test.go
bridge/gitlab/import.go
bridge/gitlab/parser/parser.go
bridge/gitlab/parser/parser_test.go

This change refactors how issue title changes from gitlab events are
detected, fixing an issue (due to upstream changing the format of the
event body from markdown-esque to html), and improving on error
handling.
The error boiled down to a change in the issue title format. Gitlab
changed this on April 17 2025 with the release of version 17.11 [0],
although the only place a reference to this change exists is in the
changelog [1], which is not linked to from the releases page.
To account for the potential future in which other fields need to be
parsed in this way, an internal parser library was introduced at
`//bridge/gitlab/parser:parser.go` with initial support for parsing
title change messages.
An issue was opened with the Gitlab team discussing the fact that this
was a breaking change …

fix: refactor how gitlab title changes are detected

---

bridge/gitlab/config.go

Closes: #1268
Change-Id: Ifc029c7058b080b3d9859eaffaa4b9febd2d80b1

fix: use correct url for gitlab PATs

---

commands/user/user_show.go
entities/bug/comment.go

+0200 is not a valid reference identifier for the time format string,
which requires a valid layout [0] using the reference time `01/02
03:04:05PM '06 -0700`.
As the documentation notes:
> It is a regrettable historic error that the date uses the American
> convention of putting the numerical month before the day.
This, combined with `-0700` being hardcoded into the layout requirements
is what likely led to the confusion that caused this issue. This change
is a fix for all `Time.Format()` calls, adjusting the time format in
place to use the correct tzdata. As a future potential improvement, we
should consider refactoring the format to use one of the constants in
the time package that are exported for the different predefined
formatting strings. This is not being done as part of this …

fix: use -0700 when formatting time

---

CONTRIBUTING.md

This change adds a missing step to the contributor onboarding
documentation (//:CONTRIBUTING.md): testing that the user has
successfully activated the development shell. This is a useful step for
users who are new to nix, and was referenced in 4.1.
Change-Id: Iea78c5a3a54e62bc8cca8803270db8d7b7f2c872

doc: clarify testing activation of the dev shell

---

.github/workflows/build-and-test.yml
bridge/github/export_test.go
bridge/github/import_test.go

This change removes extraneous variables used for the github bridge
(e2e) tests, conslidating on GITHUB_USER and GITHUB_TOKEN, which match
the variables read by the github CLI and what users would have in their
environment if they are using the vars.
We leave GITHUB_TOKEN_PRIVATE and GITHUB_TOKEN_PUBLIC for now, as those
are used in a single test to validate a minimum set of permissions.
Moving away from these will require additional refactoring.
Change-Id: I8d83e4f0c9b2556133c5ec3daca492fe1a4bd968

test: simplify github-related variables

---

internal/test/recorder.go
internal/test/test.go
internal/test/test_test.go

This change adds an internal utility library for running flaky tests
with built-in support for incremental backoff retries. This can be used
by packages within this repository by importing `internal/test` and
invoking it as such:
func SomeTest(t *testing.T) {
f := test.NewFlaky(t, &test.FlakyOptions{
// define options here
...
})
f.Run(func(t testing.TB) {
// original test logic here
...
}
}
Change-Id: I8c6138c39c381bcee408ea6b7fe9d9b6eeb48fed

test: add an internal lib for running flaky tests

---

internal/test/recorder.go
internal/test/test.go

This change adds support to //internal/test for Failed() and
FailedNow(), and expands the support for setting and detecting the
failed status on //internal/test%recorder.
Change-Id: I04e7a978cbf0ead8d28722c0a3a0fc34136e72e1

test: implement support for Failed() and FailedNow()

---

internal/test/recorder.go
internal/test/test.go

This change adds support to //internal/test%recorder for Helper(), and
improves the ergonomics around error reporting.
Change-Id: Ia1762587b16dee9ba6ca3c428c1f935eb333a63b

test: add support for Helper()

---

misc/completion/bash/git-bug
misc/completion/generate.go

This change replaces tabs inside of a raw string literal used as a patch
for the shell completion files with spaces, and removes a trailing
space. This fixes an issue where regeneration of the file would lead to
a diff.
Change-Id: I3469a859ed63fe4ef9b8b6f156ff0ce5cb7af91c

fix: remove errata from string literal

---

.github/workflows/trunk.yml

This change introduces a pipeline job called `mirror` that will push to
`refs/heads/trunk` automatically, in order to keep it in sync with the
default tree.
This job is restricted to the SoT for git-bug, and will only execute for
the first run of the workflow.
Refs: #1404
Change-Id: If65f83ce9058dd01aa74f6841dc58ac040284b18

ci: automatically mirror HEAD to trunk

---

.github/workflows/trunk.yml
nix/checks/pinact.nix

This change refactors the derivation defined in //nix/checks:pinact.nix,
rewriting it with pkgs.runCommand so that `nix flake check` actually
executes it.
Change-Id: Ic941133bcbedd8505580db71abbaaaf8326fb874

test: use pkgs.runCommand for the pinact check drv

---

.gitmessage
CONTRIBUTING.md
doc/contrib/commit-message-guidelines.md

This change provides guidelines for writing conventional commit
messages, which will be enforced in the future. This change is being
made in order to improve ergonomics for browsing the repository and its
changes, and to support better changelog generation.
Change-Id: I533ca3c66e697aaafcc1409711600017006e264a

docs(dev-infra): define stricter commit message guidelines

---

termui/help_bar.go

This change changes the help bar's background color to the "black" value
for the terminal, and increases spacing between the different commands
to improve readability.
Closes: git-bug/git-bug#1411
Change-Id: I380d1fee4ae51869876f00c76c0f952d47dd8912

feat(tui): improve readability of the help bar

---

doc/contrib/commit-message-guidelines.md

This change provides more clarity as to the type and scope requirements,
and adds in additional information with regard to hyperlinks, appropriate trailers to
use in the footer, and clarifies the difference between our requirements
and the conventional commit spec v1.0.0.
Change-Id: I7e3d4646c09728acf27c4efce24655896b8513a7

docs(dev-infra): improve commit message guidelines

---

webui/src/components/Header/Header.tsx
webui/src/components/Identity/CurrentRepository.tsx

* removes the tabbed navigation completely
* makes it possible to see the custom name of the repository
tabs (and really all not "main" nav) were not in use and the features may not work the same way in the future, so rather than redesigning, the whole tab bare was removed.
for the custom name, if it's `__default`, the the default `git-bug` text is displayed; otherwise, the name of the repo.

feat(web): simplify header navigation

---

.mailmap

This change adds //.mailmap initialized with mappings for duplicate
names and email addresses found in the repository archive. When a
duplicate was found, the name and email were chosen preferring the
longest name for the author, and the most practical email address (e.g.
if an obvious personal and professional email address existed, the
personal address was chosen).
Duplicate names were found with the following command:
git shortlog -se |\
awk 'match($0, /[0-9]+[ \t]+(.*)[ \t]+<.*>/, m) { print m[1] }' |\
sort |\
uniq -d
Duplicate email addresses were found with the following command:
git shortlog -se |\
awk 'match($0, /<[^>]+>/) { print substr($0, RSTART+1, RLENGTH-2) }' |\
sort |\
uniq -d
Change-Id: Ie0280ee336098c080cf5af8062dae20cb7a41e8e

feat(dev-infra): add initial //:.mailmap

---

.github/workflows/presubmit.yml
.github/workflows/trunk.yml

This change refactors all root pipelines (`trunk` and `presubmit`) to
limit the contents permission to read. By default, GitHub has taken the
overly-permissive approach of granting all permissions if the
`permissions` map is not explicitly defined. Usability wins out over
security, again.
Change-Id: Idaca851385fb82eefd6c7c9b8ee46b85a3f4901c

ci: limit default permissions to contents.read

---

CONTRIBUTING.md

This change adds additional information to //:CONTRIBUTING.md, meant to
provide guidance to potential contributors about how our review process
works, and how we suggest iterating and submitting changes.
Change-Id: I06073fa43d9fd37d35bc04aa5bfc0187d343b257

docs(dev-infra): add guidelines for submitting changes

---

webui/.eslintrc.js
webui/package-lock.json
webui/package.json

with this upgraded, we no longer depend on an vulnerable version of the `ws` library through an old graphql version

build(web): upgrade graphql-eslint plugin

---

CONTRIBUTING.md
commands/wipe.go
repository/config_mem.go
repository/config_testing.go
repository/gogit_config.go

This change fixes an error typically encountered in the `git-bug-wipe`
command, caused by overly zealous implementations of
//repository:config.go%ConfigWrite.RemoveAll(). This change refactors
these implementations to only attempt to remove sections that exist,
and ignore non-existent sections.
Closes: #1451
Change-Id: I66e710239915c8601dd70a78ae65eb625e093ef6

fix(cli): ignore missing sections when removing configuration

---

Makefile
commands/root.go
commands/version.go
doc/generate.go
doc/man/git-bug-version.1
doc/md/git-bug.md
doc/md/git-bug_version.md
main.go
misc/completion/generate.go
version.go

This change refactors the implementation of how the version is embedded
in the binary to reduce the number of variables necessary to determine
the version information from 3 to 1.
The legacy build variables are still supported, however, a warning will
be emitted instructing users to contact their package maintainer. The
legacy GitExacTag variable, if present, will be used to set main.version
if it is undefined. This ensures that unmigrated package builds will
continue to provide the correct version information.
The legacy build variables will be supported until 0.12.0, giving
package maintainers some time to migrate.
Change-Id: I05fea97169ea1af87b198174afe5b6663f860fd8

build: reduce complexity for setting the version
