git-bug/git-bug

- doc/queries.md
This cleans up the wording a little and clarifies a few points.
> Cleanup queries.md

- termui/label_select.go
- termui/show_bug.go
- termui/termui.go
Uses a new `labelSelect` window. The styling on `labelSelect` could use some work, but it is functional.
> Edit labels in termui

- README.md
Following your support request on Open Collective (1), here is an update to the Readme that I think will correct a few issues you reported.
Does that looks correct? Any feedback?
https://github.com/opencollective/git-bug/blob/opencollective/README.md
For now, I'm using the `images-preview` service which is not the live one, so please don't merge!
(1) https://github.com/opencollective/opencollective/issues/1368
> Open Collective integration in Readme

- commands/ls-id.go
- doc/man/git-bug-add.1
- doc/man/git-bug-bridge-configure.1
- doc/man/git-bug-bridge-pull.1
- doc/man/git-bug-bridge-rm.1
- doc/man/git-bug-bridge.1
- doc/man/git-bug-commands.1
- doc/man/git-bug-comment-add.1
- doc/man/git-bug-comment.1
- doc/man/git-bug-deselect.1
- doc/man/git-bug-label-add.1
- doc/man/git-bug-label-rm.1
- doc/man/git-bug-label.1
- doc/man/git-bug-ls-label.1
- doc/man/git-bug-ls.1
- doc/man/git-bug-pull.1
- doc/man/git-bug-push.1
- doc/man/git-bug-select.1
- doc/man/git-bug-show.1
- doc/man/git-bug-status-close.1
- doc/man/git-bug-status-open.1
- doc/man/git-bug-status.1
- doc/man/git-bug-termui.1
- doc/man/git-bug-title-edit.1
- doc/man/git-bug-title.1
- doc/man/git-bug-webui.1
- doc/man/git-bug.1
- doc/md/git-bug.md
- misc/bash_completion/git-bug
- misc/zsh_completion/git-bug
This file adds the ls-id command which returns
the bug id matching the prefix the user enters.
If no prefix entered it lists all the BugId's
Closes #47
> A command to list matching bug id from a prefix

- webui/src/Author.js
- webui/src/bug/Bug.js
- webui/src/bug/LabelChange.js
- webui/src/bug/Message.js
- webui/src/bug/SetStatus.js
- webui/src/bug/SetTitle.js
- webui/src/bug/Timeline.js
- webui/src/bug/TimelineQuery.js
Fixes #94 
The webui now uses the `Timeline` API instead of the raw `Operation`s.
> Use Timeline API instead of raw operations

- bug/op_add_comment.go
- bug/op_create.go
- bug/op_create_test.go
- bug/op_edit_comment.go
- bug/op_label_change.go
- bug/op_set_status.go
- bug/op_set_title.go
- bug/snapshot.go
- cache/bug_excerpt.go
- cache/filter.go
- cache/query.go
- cache/query_test.go
- doc/queries.md
- graphql/graph/gen_graph.go
- graphql/graphql_test.go
- graphql/resolvers/bug.go
- graphql/schema/bug.graphql
> WIP: Implement participants and actors functionalities

- cache/filter.go
- cache/identity_excerpt.go
- doc/queries.md
> Support matching identities with ID and truncated ID

- commands/ls.go
- commands/show.go
Examples:
- `git bug ls --participant=9ed1a`
- `git bug show -f=actors`
> integrate actors and participant filters into ls and show commands

- graphql/graph/gen_graph.go
- graphql/resolvers/repo.go
- graphql/schema/repository.graphql
Expose the valid labels list in the GraphQL API.
> graphql: expose valid labels

- webui/package-lock.json
- webui/package.json
- webui/src/App.js
- webui/src/Label.js
- webui/src/bug/Bug.js
- webui/src/bug/LabelChange.js
- webui/src/bug/Message.js
- webui/src/bug/SetStatus.js
- webui/src/bug/SetTitle.js
- webui/src/bug/Timeline.js
- webui/src/index.js
- webui/src/list/BugRow.js
- webui/src/list/List.js
- webui/src/list/ListQuery.js
I bumped all the webui dependencies (dependabot should close all it's PRs automatically).
I updated `material-ui` to use their new hook API. I also reworked the pagination to use React's hook for state management.
> Updates WebUI dependencies & rework the bug list pagination

- webui/package-lock.json
- webui/package.json
- webui/src/Content.js
- webui/src/bug/Message.js
This uses remark as markdown parser/processor. It can be extended with plugins if we want to have some markdown extensions.
> webui: Render markdown in messages

- bridge/github/import.go
- bridge/github/import_test.go
- bridge/github/iterator.go
- Iterator now ignore nil and empty edits
- Fix imported bugs count
- Add imported identities count
> Enhancement to Github iterator and importer

- bridge/core/bridge.go
> Consistent bridge implementations list

- bridge/github/import.go
- bridge/launchpad/import.go
- cache/multi_repo_cache.go
- cache/repo_cache.go
- cache/repo_cache_test.go
- commands/add.go
- commands/select/select_test.go
- graphql/gqlgen.yml
- graphql/graph/gen_graph.go
- graphql/models/gen_models.go
- graphql/resolvers/label.go
- graphql/resolvers/mutation.go
- graphql/resolvers/operations.go
- graphql/resolvers/query.go
- graphql/resolvers/root.go
- graphql/schema/mutations.graphql
- graphql/schema/root.graphql
- termui/termui.go
> Graphql mutation relay

- bridge/github/config.go
This fixes project visibility project choices
> fix project visibility prompt in Github bridge configuration

- bridge/github/config.go
fix panic in github configuration when choosing an URL
> fix index out of range panic in github configuration

- bridge/gitlab/import.go
fix an issue that was causing gitlab bridge to duplicate operations when running multiple imports
> bridge: fix gitlab bridge when running multiple imports. 

- bridge/core/export.go
- bridge/gitlab/export.go
- bridge/gitlab/export_test.go
- bridge/gitlab/gitlab.go
- bridge/gitlab/import.go
- commands/bridge_push.go
> Gitlab bridge exporter

- util/interrupt/cleaner.go
- util/interrupt/cleaner_test.go
> interrupt: allow to cancel a cleaner

- README.md
- doc/model.md
related to https://github.com/MichaelMure/git-bug/issues/227
> Clarify model.md a bit

- Makefile
it's a little pain to have to make these changes each time i change the branch x)
> makefile: support Darwin operating systems (xargs)

- README.md
> README: update importer implementation table

- bridge/github/import_query.go
- bridge/github/iterator.go
https://developer.github.com/v4/changelog/2019-06-04-schema-changes/
> github: follow API changes

- bridge/github/iterator.go
> bridge/github: fix iterator regression

- bug/bug.go
- bug/bug_actions_test.go
- bug/bug_test.go
- bug/clocks.go
- bug/interface.go
- repository/git.go
- repository/mock_repo.go
- repository/repo.go
A single line fix for #235 and a bunch of esthetic fixes.
> Core fixes

- Gopkg.lock
- bug/bug.go
- bug/bug_test.go
- bug/op_set_metadata.go
- bug/operation_iterator_test.go
- misc/random_bugs/create_random_bugs.go
> bug: make sure there is no Operation's hash collision

- bridge/github/export.go
- bridge/github/import.go
- bridge/gitlab/export.go
- bridge/gitlab/import.go
- bridge/launchpad/import.go
- cache/bug_cache.go
> Bridge: correctly emit NothingEvents

- bridge/core/bridge.go
- bridge/core/token.go
- bridge/github/config.go
- bridge/github/export.go
- bridge/github/import.go
- bridge/gitlab/config.go
- bridge/gitlab/export.go
- bridge/gitlab/import.go
- commands/bridge_configure.go
Support bridge configuration with global tokens for the following targets:
> Support bridge configuration with global tokens

- bridge/github/config.go
- bridge/gitlab/config.go
- commands/bridge_configure.go
> bridge: trim inputs during bridge configuration

- bridge/gitlab/config.go
- bridge/gitlab/config_test.go
> bridge/gitlab: add base url configuration

- webui/src/Content.js
- webui/src/bug/Bug.js
- webui/src/bug/Message.js
- webui/src/tag/ImageTag.js
- webui/src/tag/PreTag.js
If an image or a code block was too large the design of a bug message was broken.
This PR also adds support to open images in a new tab on a click.
> Fix column overflow in webui

- webui/package-lock.json
- webui/package.json
- webui/src/__tests__/query.js
- webui/src/list/BugRow.js
- webui/src/list/Filter.js
- webui/src/list/FilterToolbar.js
- webui/src/list/List.js
- webui/src/list/ListQuery.js
This implements basic filters (right now only open/closed issues) and improves the issue list page.
Paging is now implemented with query params, so reloading the page displays the same issues.
I implemented the query filters parsing using regexs ; this is not exactly the same as in the backend but right now it’s Good Enough™.
Because the query parsing/stringifying is a bit complex, I wrote tests for it. Those are the first tests in the webui (🎉), although they are not run by the CI right now.
Please note that the label/author/sort filters are not working right now (mainly because I need to do some kind of drop downs for that).
Also check the `TODO`s in the code.
> Issue list improvements and filtering

- bridge/core/auth/credential.go
- bridge/core/bridge.go
- bridge/core/config.go
- bridge/github/config.go
- bridge/github/github.go
- bridge/gitlab/config.go
- input/prompt.go
- generalized credential prompt with existing credentials and choices
> bridges: more refactor and cleanup

- README.md
Address comments in #387 for installation instructions.
> Include FreeBSD package section.

- cache/bug_excerpt.go
- cache/repo_cache.go
> cache: fix BugExcerpt's timestamp not properly stored

- termui/bug_table.go
- termui/help_bar.go
- termui/label_select.go
- termui/show_bug.go
> termui: make the help visually easier to parse

- termui/bug_table.go
This partially addresses #430 for the bug table, although this offers no configuration.
> Packed bugview

- go.sum
- repository/gogit_config.go
> repository: fix edge case in git config read, affecting bridges

- repository/gogit.go
> read name from both global and local config

- bug/bug.go
- entity/refs.go
- go.sum
- identity/identity.go
- identity/identity_test.go
also adds:
- listlocalidentities
- refactors refstoids into entity package
> add remove identity feature

- bridge/github/import.go
- bridge/github/import_query.go
- bridge/github/iterator.go
Supersedes #516
Deals with #385
> Fix github bridge import

- webui/src/layout/CommentInput/CommentInput.tsx
- webui/src/pages/bug/CommentForm.tsx
- webui/src/pages/new/NewBugPage.tsx
- validating to avoid empty comments
- comment button now is green
> Commit for #539

- bridge/gitlab/import.go
> Fix comparison mix-up in gitlab importer

- webui/Readme.md
- webui/src/components/BugTitleForm/BugTitleForm.tsx
- webui/src/pages/list/ListQuery.tsx
> Webui 543 ifloggedin

- webui/src/pages/list/BugRow.graphql
- webui/src/pages/list/BugRow.tsx
> Display count of comment for each bug on bug list

- go.mod
- go.sum
- repository/git_cli.go
- repository/gogit.go
See https://blog.golang.org/path-security for details
> repo: fix security issue that could lead to arbitrary code execution

- webui/.eslintrc.js
- webui/package.json
- webui/src/pages/list/Filter.tsx
- webui/src/pages/list/FilterToolbar.tsx
- webui/src/pages/list/ListIdentities.graphql
- webui/src/pages/list/ListLabels.graphql
- webui/src/pages/list/ListQuery.tsx
Changes to bug list page:
- Add dropdown menu to filter bugs by multiple authors and labels
- Add predefined filters menu
- Filter input takes full width between "predefined filter menu" and "new bug" button
PS: Displaying the color of a label within the label dropdown menu will be added in another PR.
> WebUI: Additional filters for bug list

- webui/src/components/BackToListButton.tsx
- webui/src/components/BugTitleForm/BugTitleForm.tsx
- webui/src/pages/list/ListQuery.tsx
Link instantly to:
- NewBugPage
- BackToList
> Prevent page reload for redirecting components

- webui/src/components/BugTitleForm/BugTitleForm.tsx
- webui/src/components/Header/Header.tsx
- Fix a console error which occurs when a route is unknown to the navigation bar.
E.g. users opens the detail page of a bug.
- When editing the title of an bug, only set it if the title is different form the old title.
> Minor bugfixes

- api/graphql/resolvers/mutation.go
- bridge/github/import.go
- bridge/gitlab/import.go
- bridge/jira/import.go
- bridge/launchpad/import.go
- bug/label.go
- bug/op_create.go
- bug/op_set_metadata.go
- bug/op_set_title.go
- cache/bug_cache.go
- commands/add.go
- commands/comment_add.go
- commands/label_add.go
- commands/label_rm.go
- commands/title_edit.go
- identity/version.go
- termui/termui.go
- util/text/transform.go
- util/text/validate.go
> make sure every text input is safe and validated

- repository/gogit.go
fix https://github.com/MichaelMure/git-bug/issues/497
> repository: workaround a non thread-safe path in go-git

- bug/comment.go
- bug/op_add_comment.go
- bug/op_create.go
- bug/op_create_test.go
- bug/op_edit_comment.go
- bug/op_edit_comment_test.go
- bug/snapshot.go
- bug/timeline.go
> Fix ID string in order to find correct bug instance on comment edit operation

- webui/src/components/CommentInput/CommentInput.tsx
> Make comment input vertically resizable

- webui/src/components/CommentInput/CommentInput.tsx
- webui/src/pages/bug/Message.tsx
- webui/src/pages/bug/MessageHistoryDialog.tsx
> Show placeholder for empty comment(preview)

- api/graphql/graph/gen_graph.go
- api/graphql/models/gen_models.go
- api/graphql/resolvers/mutation.go
- api/graphql/schema/mutations.graphql
- api/graphql/schema/root.graphql
- go.sum
Should implement #553 ~Still required:~
~- [ ] Marshalling~
~- [ ] Unit Tests~
~- [ ] Test if this operation actually works this way~
> GraphQL: Implement AddCommentAndCloseBug mutation

- webui/src/pages/list/BugRow.tsx
> Fix margin and alignment of comment counter for high comment count

- .github/workflows/go.yml
- webui/packed_assets.go
format go code and enforce it via CI
> Add Linter Step

- bridge/github/import.go
> Fix: github import, some issue titles cause error

- commands/ls.go
This PR resolves #699 by introducing another `compact` format to the ls command.
The `compact` format should print a bug per line while never exceeding the 79 column to prevent wrapping in smaller terminals.
An image  with description of different `ls` outputs can be found [here](https://github.com/MichaelMure/git-bug/issues/699#issuecomment-899599628)
>  I would like to most humbly request that this format should be the default, it is compact and informative.
_Originally posted by @jech in https://github.com/MichaelMure/git-bug/issues/699#issuecomment-899771039_
I would add a follow up commit if nothing speaks against it. @MichaelMure
PS: I tried to port the default format over to "go templates". This could be an interesting solution for the future, as users could then define their own …
> Command ls: Add compact format

- .github/workflows/go.yml
- go.mod
This is needed for a gqlgen update.
> build: require go 1.16

- bridge/gitlab/config.go
Fixes https://github.com/MichaelMure/git-bug/issues/772
> Allow new gitlab PAT format

- .github/workflows/go.yml
> fix(884): scan PRs for insecure practices

- bridge/github/client.go
In particular, for the case of when the local clock is wrong, but also if the returned value is bogus.
> github: sanitize rate limit waiting time

- api/http/git_file_handlers_test.go
- cache/repo_cache.go
- commands/execenv/env.go
- commands/webui.go
> cache: tie the last printf in an event to make the core print free

- cache/repo_cache_test.go
> refactor(TestCache): guarantee test caches are closed when tests finish

- .github/workflows/benchmark.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
- cache/repo_cache_test.go
- go.mod
> fix: resolve Go vulnerabilities

- cache/repo_cache.go
- cache/subcache.go
- commands/execenv/env.go
- commands/execenv/env_testing.go
- commands/webui.go
- entities/identity/identity.go
- entity/dag/entity.go
- entity/streamed.go
- go.mod
- go.sum
One issue remaining is that writing the cache takes significant time, but I don't know how to reflect that nicely to the user.
> commands: add a nice terminal progress bar when building the cache

- .codespellrc
- .github/workflows/codespell.yml
- bridge/core/bridge.go
- bridge/github/client.go
- bridge/github/import_test.go
- bridge/gitlab/export.go
- bridge/jira/client.go
- bridge/launchpad/launchpad_api.go
- doc/howto-github.md
- entities/identity/key.go
- entity/dag/op_set_metadata_test.go
- entity/dag/operation_pack.go
- webui/src/components/Header/Header.tsx
while waiting on cache rebuild while troubleshooting https://github.com/MichaelMure/git-bug/issues/995 decided to contribute.  Subject line says it all, the diff individual commits might give a bit more detail.
> Fix typos, provide configuration and github workflow for codespell

- commands/webui.go
fix https://github.com/MichaelMure/git-bug/issues/1014#issuecomment-1437175472
> webui: also teardown cleanly on SIGTERM

- .github/workflows/benchmark.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/codespell.yml
- .github/workflows/go.yml
- .github/workflows/nodejs.yml
- .github/workflows/release.yml
- webui/src/components/Header/Header.tsx
```
- feat: update action library versions
- feat: add concurrency limits to all pipelines
- fix: bump to go v1.22.5
- fix: correct typo: acceps => accepts
```
---
This is a **stack of logically independent commits** and should be **rebased** instead of merged with a merge commit, or squashed.
> A lil' bit of TLC for the pipelines

- .editorconfig
- .envrc
- .git-blame-ignore-revs
- .gitignore
- .gitmessage
- CONTRIBUTING.md
- flake.lock
- flake.nix
```
- feat: add initial editorconfig configuration file
- feat: add a common file for git-blame ignored revisions
- feat: add a commit message template
- feat: add initial nix development shell
```
---
This is a **stack of independent commits**. It should be **rebased** on top of HEAD, not merged with a merge commit, or squashed.
> dev-infra: flake-based dev shell, editorconfig, git message template, git-blame-ignore-revs

- .github/workflows/cron.yml
```
fix: correct path for reusable workflow: lifecycle
Change-Id: I02c6e1f183e4b6ee67c0a4d0dcb7c5fbeff361ac
```
> fix: correct path for reusable workflow: lifecycle

- doc/man/git-bug-bridge-new.1
- doc/man/git-bug-bug-deselect.1
- doc/man/git-bug-bug-select.1
- doc/man/git-bug-bug.1
- doc/md/git-bug_bridge_new.md
- misc/completion/bash/git-bug
- misc/completion/fish/git-bug
- misc/completion/powershell/git-bug
Closes: #1209
Change-Id: Id19d5013b04ef5c99a99d367bbf3d618b8be068b
> chore: regenerate command completion and documentation

- .github/workflows/lifecycle.yml
This label is planned to replace lifecycle/frozen, as the language is a
bit more clear.
Refs: #1333
Change-Id: Ided8be62e9faaecbe901f235d18d218e05a33ece
> feat: support new exclusion label: lifecycle/pinned

- .github/workflows/lifecycle.yml
This change removes lifecycle/frozen from the lifecycl workflow, as it
is no longer used.
Closes: #1333
Change-Id: Ie4a6512c7143096a6edd051591f0b1c10bbdef48
> feat: remove lifecycle/frozen

- .github/workflows/build-and-test.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/trunk.yml
- flake.lock
- go.mod
Change-Id: Iaa7018583fae53ede7b744ec6dee59db01459286
> feat: bump to go v1.24.2

- repository/gogit.go
This change introduces a new method for resolving the URI for a given
remote (by name), ensuring that the URI is rewritten following the rules
defined in `url.*.insteadOf` configuration.
When `go-git@69aefb67315d775bf73df836b1e3ba5a3b321198` lands in a
release (and we update go-git to that release), this should be
refactored to use `config.URL.InsteadOfs()`, which supports multiple
`url.*.insteadOf` configuration blocks instead of the current limitation
of always taking the last definition.
Closes: #944
Change-Id: Iffd111a1f4c42eff12613dcbd1b0d27df415f5e8
> fix: resolve the remote URI using url.*.insteadOf

- flake.nix
Change-Id: Ibafa6e2a23922b2ec80bc1be2d77972765dc690b
> feat(dev-infra): add gopls to the development shell

- cache/repo_cache_test.go
This test regularly fails on Windows. It should be rewritten so as to
avoid flakiness, however, marking it as flaky as a stop-gap enables a
better pipeline experience without requiring the upfront cost of
rewriting it.
Change-Id: Ia0dc13864e0fdf463b01a2a31b8d59b692c0c924
> test: mark TestCache as flaky

- .gitmessage
I got [this patch to my repo at Sourcehut](https://lists.sr.ht/~mcepl/devel/<20250510074052.2005600-1-keeperotphones@gmail.com>).
> Spelling corrections

- .editorconfig
This change updates //:.editorconfig to improve the alignment between
its configuration settings and the output from formatters, in an effort
to reduce format cycles during iteration.
Change-Id: I8e1af63a961bc8ca29d8b4a41f80ae7251a96f26
> feat(dev-infra): improve //:.editorconfig alignment with formatters

- CONTRIBUTING.md
Change-Id: Ie21eb3761c8e632d1ff66c5b3fc2474f97e3364e
> docs(dev-infra): add a section about commit messages to //:CONTRIBUTING.md

- CHANGELOG.md
Change-Id: I68b8c234100ae91a6ad6b838211ce2ce7dd8feca
> docs(changelog): bump for v0.10.1

- CONTRIBUTING.md
Change-Id: I0a21fbc9eb6d11afb647c8e51e40d3a5f5155792
> docs(dev-infra): fix missing link to //:CHANGELOG.md

- .github/workflows/cron.yml
This change adds a new pipeline named `cron`, with an initial task that
will handle automatically updating the default branch for this
repository.
Ref: #1404
Change-Id: Iff5529938d9be50de9733f98e72e86c4480e1d6e
> feat(dev-infra): add pipeline: cron/rename-default-branch

- .github/workflows/trunk.yml
Closes: #1404
Change-Id: Iee167b1de8df7019d39157fb258aa612942ab4d4
> feat(dev-infra): set trunk workflow to run on branch: trunk
